### ISSUE TITLE
Die App startet nicht!

### ISSUE THREAD

**Issue by NiklasWyld** [FuchsBene/HarmonySync#4]
Wenn ich versuche die App zu starten, gibt es Fehler. (Zmd. in der "main" Branch sollte immer eine getestete stabile Version sein!)

```
Traceback (most recent call last):
  File ".\HarmonySync.py", line 8, in <module>
    from backend import *
ModuleNotFoundError: No module named 'backend'
```
Es scheint so, als hättest du imports, die schon lange entfernt sind oder es nie gegeben hat.

**Comment by NiklasWyld** [comment]
Sobald man den backend import entfernt, gibt es den nächsten Fehler:
```
Traceback (most recent call last):
  File ".\HarmonySync.py", line 16, in <module>
    save_data = json.loads(open(f"{app_path}/save_data.json", "r").read())
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\nikla\\HarmonySync/save_data.json'
```
